---
name: pre-commit
"on":
  pull_request:
  push:
    branches: [main]

jobs:
  run-precommit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.x"
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.x"
      - name: Install tools
        run: |
          pip install pre-commit
          dotnet tool install -g csharpier
      - name: Run pre-commit
        run: pre-commit run --all-files
